### ISSUE TITLE
Error: invalid model_name entered to get vehicle model length

### ISSUE THREAD

**Issue by jeffchen006** [CenturyLiu/Carla-GUI#1]
```
Error: invalid model_name entered to get vehicle model length
destroyed all actors
Traceback (most recent call last):
  File "/home/zhiychen/Documents/Carla-GUI/backend/intersection_backend.py", line 349, in <module>
    main()
  File "/home/zhiychen/Documents/Carla-GUI/backend/intersection_backend.py", line 286, in main
    init_intersection.add_follow_vehicle(follow_distance = 20.0, stop_choice = "penetrate", penetrate_distance = 2.0)
  File "/home/zhiychen/Documents/Carla-GUI/backend/initial_intersection.py", line 116, in add_follow_vehicle
    self._add_full_path_vehicle("follow",gap = gap, model_name = model_name, obey_traffic_lights = obey_traffic_lights, run = run, safety_distance = safety_distance, vehicle_color = vehicle_color)
  File "/home/zhiychen/Documents/Carla-GUI/backend/initial_intersection.py", line 189, in _add_full_path_vehicle
    gap += bb.x / 2 + curr_length / 2
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

Please see the above error. The error happens when I run intersection_backend.py under Carla-GUI/ folder.

**Comment by jeffchen006** [comment]
Hello, the reason of this error is that if you run intersection_backend.py under Carla-GUI/ folder. You may fail to read vehicle_length_config.txt which stores information about vehicle lengths. 
You should run it under Carla-GUI/gui_interface/ folder.

**Comment by jeffchen006** [comment]
That works. The above explanation is pretty clear. I will close this issue.
