### ISSUE TITLE
freeway_window.py crashes after starting the simulation

### ISSUE THREAD

**Issue by Mohamed-Fasil** [CenturyLiu/Carla-GUI#6]
Hello,

I tried to follow the video in documentation to run a scenario (https://www.youtube.com/watch?v=NmfEndjB0Tw) and when I select the camera view and hit play simulation the window crashes with the following error. The vehicles disappear in Carla window and the scenario doesn't run further.

D:\Carla\Carla-GUI-master\gui_interface>python freeway_window.py
WARNING: Version mismatch detected: You are trying to connect to a simulator that might be incompatible with this API
WARNING: Client API version     = 0.9.11-4-gfe3cb686
WARNING: Simulator API version  = 0.9.11-4-gfe3cb686-dirty
D:\Carla\Carla-GUI-master\backend\vehicle_length_config.txt
{'vehicle.audi.a2': '1.8593107461929321', 'vehicle.audi.tt': '2.073613166809082', 'vehicle.mercedes-benz.coupe': '2.521892547607422', 'vehicle.bmw.grandtourer': '2.3195438385009766', 'vehicle.yamaha.yzf': '1.0953842401504517', 'vehicle.audi.etron': '2.446002721786499', 'vehicle.nissan.micra': '1.8344237804412842', 'vehicle.bh.crossbike': '0.7546613812446594', 'vehicle.lincoln.mkz2017': '2.452350616455078', 'vehicle.gazelle.omafiets': '0.9217206835746765', 'vehicle.tesla.cybertruck': '3.1821160316467285', 'vehicle.dodge_charger.police': '2.505488157272339', 'vehicle.tesla.model3': '2.4044108390808105', 'vehicle.harley-davidson.low_rider': '1.175087809562683', 'vehicle.toyota.prius': '2.2691667079925537', 'vehicle.seat.leon': '2.1039369106292725', 'vehicle.kawasaki.ninja': '1.021842122077942', 'vehicle.nissan.patrol': '2.259999990463257', 'vehicle.mini.cooperst': '1.9010963439941406', 'vehicle.jeep.wrangler_rubicon': '1.9340534210205078', 'vehicle.mustang.mustang': '2.452350616455078', 'vehicle.volkswagen.t2': '2.2368555068969727', 'vehicle.chevrolet.impala': '2.684596538543701', 'vehicle.citroen.c3': '1.9876738786697388', 'vehicle.diamondback.century': '0.8281218409538269', 'vehicle.bmw.isetta': '1.1012483835220337', 'vehicle.carlamotors.carlacola': '2.5996146202087402'}
destroyed all actors
0.03388217203628033
find a path with 2 waypoints
0.033878357342496626
find a path with 2 waypoints
0.03387454264871371
find a path with 2 waypoints
0.03386691326115023
find a path with 2 waypoints
0.03385928134865447
find a path with 2 waypoints
0.000579833984375
find a path with 2 waypoints
0.0005798371214530808
find a path with 2 waypoints
0.00057220458984375
find a path with 2 waypoints
0.0005722077687493077
find a path with 2 waypoints
0.00057220458984375
find a path with 2 waypoints
0.0005722077687493077
find a path with 2 waypoints
0.00055694580078125
find a path with 2 waypoints
0.00055694580078125
find a path with 2 waypoints
0.00054931640625
find a path with 2 waypoints
0.00066375732421875
find a path with 2 waypoints
0.0010604875550839392
find a path with 2 waypoints
0.0015487682643190639
find a path with 2 waypoints
0.002090457582122801
find a path with 2 waypoints
0.0027465846803440457
find a path with 2 waypoints
0.0034866353875953222
find a path with 2 waypoints
0.0043029823201751125
find a path with 2 waypoints
0.005218511436414806
find a path with 2 waypoints
0.005371099168601338
find a path with 2 waypoints
0.005371099168601338
find a path with 2 waypoints
0.005355840394976432
find a path with 2 waypoints
0.005371099168601338
find a path with 2 waypoints
0.005371099168601338
find a path with 2 waypoints
0.005355840394976432
find a path with 2 waypoints
0.005371099168601338
find a path with 2 waypoints
0.005371099168601338
find a path with 2 waypoints
0.005371096797963925
find a path with 2 waypoints
0.005371096797963925
find a path with 2 waypoints
0.005355838017585077
find a path with 2 waypoints
0.005371099168601338
find a path with 2 waypoints
0.005371099168601338
find a path with 2 waypoints
0.005371099168601338
find a path with 2 waypoints
0.005355840394976432
find a path with 2 waypoints
0.005371099168601338
find a path with 2 waypoints
0.005386357942313708
find a path with 2 waypoints
0.005371099168601338
find a path with 2 waypoints
0.005371099168601338
find a path with 2 waypoints
0.005371099168601338
find a path with 2 waypoints
0.005386357942313708
find a path with 2 waypoints
0.005371099168601338
find a path with 2 waypoints
0.005111697538574126
find a path with 2 waypoints
0.004821783379659617
find a path with 2 waypoints
0.004531863963963774
find a path with 2 waypoints
0.004257205993896717
find a path with 2 waypoints
0.003997806829348498
find a path with 2 waypoints
0.003738407699426694
find a path with 2 waypoints
0.003494267380390608
find a path with 2 waypoints
0.0032501243089838334
find a path with 2 waypoints
0.0029907250890916543
find a path with 2 waypoints
0.0028076197790050986
find a path with 2 waypoints
0.0025634794008148466
find a path with 2 waypoints
0.0023803718579119898
find a path with 2 waypoints
0.002197268936366659
find a path with 2 waypoints
0.0019531287252867457
find a path with 2 waypoints
0.001770020558915991
find a path with 2 waypoints
0.0016479503225393483
find a path with 2 waypoints
0.0014648449917629065
find a path with 2 waypoints
0.0012817397004074233
find a path with 2 waypoints
0.001129150390625
find a path with 2 waypoints
0.00103759765625
find a path with 2 waypoints
0.00091552734375
find a path with 2 waypoints
0.0007934593237330258
find a path with 2 waypoints
0.0006713894280465688
find a path with 2 waypoints
0.00054931640625
find a path with 2 waypoints
0.00045776764550073846
find a path with 2 waypoints
0.000396728515625
find a path with 2 waypoints
0.00030517578125
find a path with 2 waypoints
0.000244140625
find a path with 2 waypoints
0.00018310546875
find a path with 2 waypoints
9.1552734375e-05
find a path with 2 waypoints
6.103515625e-05
find a path with 2 waypoints
3.0517578125e-05
find a path with 2 waypoints
0.07223659434981967
find a path with 2 waypoints
0.0
find a path with 2 waypoints
0.0
find a path with 2 waypoints
0.0
find a path with 2 waypoints
0.0
find a path with 2 waypoints
0.0
find a path with 2 waypoints
0.0
find a path with 2 waypoints
0.0
find a path with 2 waypoints
0.0
find a path with 2 waypoints
0.0
find a path with 2 waypoints
0.0
find a path with 2 waypoints
0.0
find a path with 2 waypoints
0.0
find a path with 2 waypoints
0.0
find a path with 2 waypoints
0.0
find a path with 2 waypoints
3.0517578125e-05
find a path with 2 waypoints
6.106495129998063e-05
find a path with 2 waypoints
6.103515625e-05
find a path with 2 waypoints
0.46231108724459474
find a path with 2 waypoints
0.3990474358169232
find a path with 2 waypoints
0.2718415745149904
find a path with 2 waypoints
0.42594504159294994
find a path with 2 waypoints
0.11240474303402116
find a path with 4 waypoints
1.1422364005372647
find a path with 2 waypoints
1.1454936024206408
find a path with 2 waypoints
1.1482192706208967
find a path with 2 waypoints
1.150618647623521
find a path with 2 waypoints
1.1526617704948496
find a path with 2 waypoints
1.1543745753991417
find a path with 2 waypoints
1.1558721441248383
find a path with 2 waypoints
1.157140343120106
find a path with 2 waypoints
0.5812000324406872
find a path with 2 waypoints
0.4842978621427751
find a path with 2 waypoints
0.371228462024837
find a path with 2 waypoints
0.23935470176271953
find a path with 2 waypoints
0.6537331013776652
find a path with 2 waypoints
0.581194523455877
find a path with 2 waypoints
0.4842562120186708
find a path with 2 waypoints
0.3711928163229181
find a path with 2 waypoints
0.239324173190679
find a path with 2 waypoints
0.6537962637185405
find a path with 2 waypoints
0.5811976662099589
find a path with 2 waypoints
0.4842545428416272
find a path with 2 waypoints
0.37121433766115064
find a path with 2 waypoints
0.2393588437887546
find a path with 2 waypoints
0.6537461953037191
find a path with 2 waypoints
0.5811997072884343
find a path with 2 waypoints
0.4842697777208037
find a path with 2 waypoints
0.37103694752398186
find a path with 2 waypoints
0.09893987090233446
find a path with 2 waypoints
0.0
find a path with 2 waypoints
0.0
find a path with 2 waypoints
0.0
find a path with 2 waypoints
0.0
find a path with 2 waypoints
0.0
find a path with 2 waypoints
0.0
find a path with 2 waypoints
0.0
find a path with 2 waypoints
0.0
find a path with 2 waypoints
1.52587890625e-05
find a path with 2 waypoints
1.52587890625e-05
find a path with 2 waypoints
0.0
find a path with 2 waypoints
0.0
find a path with 2 waypoints
3.0517578125e-05
find a path with 2 waypoints
1.52587890625e-05
find a path with 2 waypoints
1.52587890625e-05
find a path with 2 waypoints
1.52587890625e-05
find a path with 2 waypoints
3.0517578125e-05
find a path with 2 waypoints
1.52587890625e-05
find a path with 2 waypoints
3.0517578125e-05
find a path with 2 waypoints
0.000732421875
find a path with 2 waypoints
0.0002593994140625
find a path with 2 waypoints
0.0004425048828125
find a path with 2 waypoints
0.0006256103515625
find a path with 2 waypoints
0.08143883183078994
find a path with 2 waypoints
0.17506022662263412
find a path with 2 waypoints
0.27345577800491616
find a path with 2 waypoints
0.2958809907257971
find a path with 2 waypoints
0.2962479572914818
find a path with 2 waypoints
0.29661492512922993
find a path with 2 waypoints
0.30425795704425196
find a path with 2 waypoints
0.30088600279088595
find a path with 2 waypoints
0.20775601992653048
find a path with 2 waypoints
0.11238357116242928
find a path with 2 waypoints
0.0149688720703125
find a path with 2 waypoints
0.08227559437712391
find a path with 2 waypoints
0.10044883555317505
find a path with 2 waypoints
0.0005645751953125
find a path with 2 waypoints
0.16644441612989758
find a path with 2 waypoints
0.11423820343641036
find a path with 2 waypoints
0.023929770779316874
find a path with 2 waypoints
0.1716596164189235
find a path with 2 waypoints
0.1086595929141461
find a path with 2 waypoints
0.02989827236112986
find a path with 2 waypoints
0.17802346215382073
find a path with 2 waypoints
0.10187069732408671
find a path with 2 waypoints
0.03715256636946633
find a path with 2 waypoints
0.18575809402627386
find a path with 2 waypoints
0.09362102617379217
find a path with 2 waypoints
0.04596235005362304
find a path with 2 waypoints
0.19517603159674365
find a path with 2 waypoints
0.08351922411964981
find a path with 2 waypoints
0.05675655865055507
find a path with 2 waypoints
0.20665445993546044
find a path with 2 waypoints
0.07128929765218334
find a path with 2 waypoints
0.06986396165345288
find a path with 2 waypoints
0.22070174301187395
find a path with 2 waypoints
0.05628384657974932
find a path with 2 waypoints
0.08593313249413674
find a path with 2 waypoints
0.23777359094328088
find a path with 2 waypoints
0.0379941886682314
find a path with 2 waypoints
0.10551173164379178
find a path with 2 waypoints
0.258687623854246
find a path with 2 waypoints
0.015700930636607754
find a path with 2 waypoints
0.12923367416427947
find a path with 2 waypoints
0.12493549858320255
find a path with 2 waypoints
0.0005676597667766808
find a path with 2 waypoints
0.14668219877853986
find a path with 2 waypoints
0.13530905318880812
find a path with 2 waypoints
0.0014248800695713809
find a path with 2 waypoints
0.14755976125481243
find a path with 2 waypoints
0.1344118103907365
find a path with 2 waypoints
0.6653475088135883
find a path with 4 waypoints
0.6381828268698861
find a path with 2 waypoints
0.46063076942497866
find a path with 2 waypoints
0.29459025199288746
find a path with 2 waypoints
0.5491125550845158
find a path with 2 waypoints
0.37717332733142067
find a path with 2 waypoints
0.6264576974700523
find a path with 2 waypoints
0.4496597385287077
find a path with 2 waypoints
0.28428775004319
find a path with 2 waypoints
0.15343262877374872
find a path with 2 waypoints
0.12814973513911282
find a path with 2 waypoints
0.00916813265211465
find a path with 2 waypoints
0.15588739759888268
find a path with 2 waypoints
0.12554818144986746
find a path with 2 waypoints
0.011794047048271599
find a path with 2 waypoints
0.15869997734985028
find a path with 2 waypoints
0.12250318832651752
find a path with 2 waypoints
0.015079822049475961
find a path with 2 waypoints
0.16219259332182168
find a path with 2 waypoints
0.11879900514061875
find a path with 2 waypoints
0.019128704251482255
find a path with 2 waypoints
0.1664240833138105
find a path with 2 waypoints
0.11423088636773002
find a path with 2 waypoints
0.02401081854772851
find a path with 2 waypoints
0.17167125080110088
find a path with 2 waypoints
0.10864111224267824
find a path with 2 waypoints
0.02996527818174179
find a path with 2 waypoints
0.17803945923895406
find a path with 2 waypoints
0.10183384758195228
find a path with 2 waypoints
0.037256613807488986
find a path with 2 waypoints
0.18581844834103728
find a path with 2 waypoints
0.0936161516283956
find a path with 2 waypoints
0.04604244973917781
find a path with 2 waypoints
0.1952264453136983
find a path with 2 waypoints
0.08346625123805787
find a path with 2 waypoints
0.052551588529356284
find a path with 2 waypoints
0.04058866572457988
find a path with 2 waypoints
0.04058866572457988
find a path with 2 waypoints
0.04058866572457988
find a path with 2 waypoints
0.04058866572457988
find a path with 2 waypoints
0.04058866572457988
find a path with 2 waypoints
0.04058866572457988
find a path with 2 waypoints
0.04058866572457988
find a path with 2 waypoints
0.040588562470214605
find a path with 2 waypoints
0.04058866572457988
find a path with 2 waypoints
0.04058866572457988
find a path with 2 waypoints
0.04058866572457988
find a path with 2 waypoints
0.04058866572457988
find a path with 2 waypoints
0.04058866572457988
find a path with 2 waypoints
0.04058866572457988
find a path with 2 waypoints
0.04058866572457988
find a path with 2 waypoints
0.040558148362268495
find a path with 2 waypoints
0.04054278631028695
find a path with 2 waypoints
0.040558148362268495
find a path with 2 waypoints
0.040558148362268495
find a path with 2 waypoints
0.040558148362268495
find a path with 2 waypoints
0.04057340704338361
find a path with 2 waypoints
0.04057340704338361
find a path with 2 waypoints
0.04057340704338361
find a path with 2 waypoints
0.040558148362268495
find a path with 2 waypoints
4.57763671875e-05
find a path with 2 waypoints
7.62939453125e-05
find a path with 2 waypoints
0.0001068115234375
find a path with 2 waypoints
0.0001373291015625
find a path with 2 waypoints
0.0001856311807341986
find a path with 2 waypoints
0.0002288818359375
find a path with 2 waypoints
0.1200942428508277
find a path with 2 waypoints
0.048941083426259156
find a path with 2 waypoints
0.23122277254590795
find a path with 2 waypoints
0.0006589606592312373
find a path with 2 waypoints
0.1973956153096972
find a path with 2 waypoints
0.05268117198863642
find a path with 2 waypoints
0.14081117769683785
find a path with 2 waypoints
0.11279102938912762
find a path with 2 waypoints
0.07696497052657608
find a path with 2 waypoints
0.18053952125782552
find a path with 2 waypoints
0.004974107794155496
find a path with 2 waypoints
0.20195877753948718
find a path with 2 waypoints
0.047824377492771915
find a path with 2 waypoints
0.14595981772371552
find a path with 2 waypoints
0.10735213551848295
find a path with 2 waypoints
0.0827725850147348
find a path with 2 waypoints
0.17435041881832852
find a path with 2 waypoints
0.01151692167836895
find a path with 2 waypoints
0.20886746720110164
find a path with 2 waypoints
0.0404582821177132
find a path with 2 waypoints
0.15377807692890957
find a path with 2 waypoints
0.09901487862026274
find a path with 2 waypoints
0.09160808161818473
find a path with 2 waypoints
0.1649990049045103
find a path with 2 waypoints
0.021479849989075202
find a path with 2 waypoints
0.21945755080904256
find a path with 2 waypoints
0.02921441314380944
find a path with 2 waypoints
0.16570190369014526
find a path with 2 waypoints
0.08636167305105914
find a path with 2 waypoints
0.10504420363987094
find a path with 2 waypoints
0.15073541052691108
find a path with 2 waypoints
0.03667154333946359
find a path with 2 waypoints
0.23556001669644971
find a path with 2 waypoints
destroyed all actors
Traceback (most recent call last):
  File "D:\Carla\Carla-GUI-master\gui_interface\start_sim_pop_up.py", line 75, in process_start
    self.parent_window.run()
  File "D:\Carla\Carla-GUI-master\gui_interface\freeway_window.py", line 990, in run
    self.freewayenv.SectionBackend(spectator_mode=spec_mode,allow_collision=allow_collisions,enable_human_control=control_mode)
  File "..\backend\section_environment.py", line 521, in SectionBackend
    ego_end = ego_vehicle.pure_pursuit_control_wrapper()
  File "..\backend\multiple_vehicle_control.py", line 315, in pure_pursuit_control_wrapper
    throttle = self.speed_control() # get the throttle control based on reference and current speed
  File "..\backend\multiple_vehicle_control.py", line 162, in speed_control
    _,y0,x0 = control.forced_response(self.sys,U = U0,X0 = self.init_values[0]) # y0 is the next values, x0 is the state evolution
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by Mohamed-Fasil** [comment]
@CenturyLiu It still crashes and the error message persists
